AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway - RestAPI

Parameters:
  ApplicationPrefix:
    Type: String
    Description: prefix to attach to resources
    Default: dev
  ApplicationName:
    Type: String
    Description: Name to attach to alias.
    Default: 'UtopiaAirlines'

Resources:
  APIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join ['',[!Ref ApplicationPrefix,"-",!Ref ApplicationName]]
      Description: 'UtopiaAirlines RestAPI Gateway'
      Body:
        Fn::Transform:
            Name: 'AWS::Include'
            Parameters:
              Location: s3://utopiaairlinesapigatewayswagger/utopiaairlines-apigateway.yaml
      
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref APIGateway
      Description: 'dev deployment'
      StageName: dev