AWSTemplateFormatVersion: "2010-09-09"
Description: Description of your Application/Microservice etc.

# Used to pass parameters from cli to CloudFormation. e.g. You can pass the Environment you are deploying to.
# This is useful to implement conditions.
Parameters:
  ApplicationEnvironment:
    Type: String
    Default: dev
  ApplicationName:
    Type: String
    Default: UtopiaMS
  ECRepositoryUri:
    Type: String
    Description: Full URI for docker image to run in container
  DBHost:
    Type: String
    Default: utopiaairlines-mysql.clufugeeqpsu.us-east-1.rds.amazonaws.com
  DBPassword:
    Type: String
  DBPort:
    Type: String
    Default: 3306
  DBName:
    Type: String
    Default: utopia
  DBUsername:
    Type: String
    Default: aws
  TGArn:
    Type: String
  ExecutionRoleArn:
    Type: String
    Default: arn:aws:iam::466486113081:role/ECSTaskExecutionRole
  SubnetID:
    Type: String
    Default: subnet-56ebde1b
  GmailEmail:
    Type: String
  GmailPassword:
    Type: String
  JWT:
    Type: String

Conditions:
  AirplaneMS: !Equals [!Ref ApplicationName, UtopiaAirplaneMS]
  AirportMS: !Equals [!Ref ApplicationName, UtopiaAirportMS]
  FlightMS: !Equals [!Ref ApplicationName, UtopiaFlightMS]

Resources:
  AppCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ["", [!Ref ApplicationName, "-Cluster"]]

  ServicesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: open ports
      VpcId: vpc-05060d52e0ec4513c
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8089
          CidrIp: 0.0.0.0/0

  # Fargate Service
  AppService:
    Type: AWS::ECS::Service # Type of AWS Service
    Properties: # Different services have multiple properties.
      ServiceName: !Ref ApplicationName
      Cluster: !Ref AppCluster # Can be created in this same CFT template
      TaskDefinition: !Ref AppTaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: !Join ["-", [!Ref ApplicationName, "Container"]]
          ContainerPort:
            !If [
              AirportMS,
              8080,
              !If [AirplaneMS, 8081, !If [FlightMS, 8082, 80]],
            ]
          TargetGroupArn: !Ref TGArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups:
            - !Ref ServicesSecurityGroup

  # Fargate Task Definition
  AppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${ApplicationName}-${ApplicationEnvironment}
      RequiresCompatibilities:
        - FARGATE
      Memory: "4096"
      Cpu: "2048"
      NetworkMode: awsvpc
      ExecutionRoleArn: !Sub ${ExecutionRoleArn}
      TaskRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: !Join ["-", [!Ref ApplicationName, "Container"]]
          Image: !Ref ECRepositoryUri
          PortMappings:
            - ContainerPort:
                !If [
                  AirportMS,
                  8080,
                  !If [AirplaneMS, 8081, !If [FlightMS, 8082, 80]],
                ]
              Protocol: tcp
          Environment:
            - Name: APPLICATION_NAME
              Value: !Sub ${ApplicationName}
            - Name: APPLICATION_ENVIRONMENT
              Value: !Ref ApplicationEnvironment
            - Name: AWS_REGION
              Value: !Ref AWS::Region
            - Name: DB_URL
              Value:
                !Join [
                  "",
                  [
                    "jdbc:mysql://",
                    !Ref DBHost,
                    ":",
                    !Ref DBPort,
                    "/",
                    !Ref DBName,
                  ],
                ]
            - Name: DB_USERNAME
              Value: !Ref DBUsername
            - Name: DB_PASSWORD
              Value: !Ref DBPassword
            - Name: EMAIL_ADDRESS
              Value: !Ref GmailEmail
            - Name: EMAIL_PASSWORD
              Value: !Ref GmailPassword
            - Name: JSON_WEB_TOKEN_SECRET
              Value: !Ref JWT
          Essential: true
          Memory: 2048
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/smoothstack/${ApplicationName}/${ApplicationEnvironment}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
              awslogs-create-group: "true"

  # Role with permissions that a task needs to do its job e.g. kinesis read, dynamo r/w, cloudwatch metrics
  TaskPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "ECS-TaskPolicy-${ApplicationName}-${ApplicationEnvironment}"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          # Cloudwatch monitoring
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
            Resource: "*"
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource:
              - arn:aws:logs:*:*
      Roles:
        - !Ref TaskExecutionRole

  #IAM for application container (task)
  TaskExecutionRole:
    Type: AWS::IAM::Role
    # Description: IAM Role for Task
    Properties:
      RoleName: !Sub "ECS-TaskExecutionRole-${ApplicationName}-${ApplicationEnvironment}"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Tags:
        - Key: ApplicationName
          Value: !Ref ApplicationName
        - Key: ApplicationEnvironment
          Value: !Ref ApplicationEnvironment
