AWSTemplateFormatVersion: '2010-09-09'
Description: Description of your Application/Microservice etc.

Resources:
  Database:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: "db.t2.micro"

  # DB  Values
  AppSecret:
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub 'smoothstack/${ApplicationEnvironment}/database-creds'
      Description: "RDS DB cluster admin credentials"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "database_user"}'
        GenerateStringKey: "password"
        PasswordLength:  30
        ExcludeCharacters: '"@/'
        ExcludePunctuation: true