AWSTemplateFormatVersion: '2010-09-09'
Description: Description of your Application/Microservice etc.

Resources:
  Database:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: "db.t2.micro"
  
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:

  Subnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "?"
      VpcId: {}

  Subnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: "?"
      VpcId: {}

  SubnetSecrets:
    Type: "AWS::SecretsManager::Secret"
      Properties:
        Description: 'Secret Subnet ID'
        Name: !Sub 'smoothstack/${ApplicationEnvironment}/subnetIDs-1'
        SecretString: !Sub '{"subnet1":"${Subnet1}","subnet2":"${Subnet2}}'

# DB  Values
  AppSecret:
    Type: "AWS::SecretsManager::Secret"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub 'smoothstack/${ApplicationEnvironment}/database-creds'
      Description: "RDS DB cluster admin credentials"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "database_user"}'
        GenerateStringKey: "password"
        PasswordLength:  30
        ExcludeCharacters: '"@/'
        ExcludePunctuation: true